//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnamnesisNutricion
    {
        public int IdAnamnesis { get; set; }
        public string DesayunoNutri { get; set; }
        public string MediaMañanaNutri { get; set; }
        public string AlmuerzoNutri { get; set; }
        public string MediaTardeNutri { get; set; }
        public string CenaNutri { get; set; }
        public string AlergicoNutri { get; set; }
        public string SuplementacionNutri { get; set; }
        public string AlimentoNoDeseados { get; set; }
        public string EdadNutri { get; set; }
        public string PesoNutri { get; set; }
        public string TallaNutri { get; set; }
        public string ImcNutri { get; set; }
        public string EscapularNutri { get; set; }
        public string TricepsNutri { get; set; }
        public string BicepsNutri { get; set; }
        public string AbdomenNutri { get; set; }
        public string MusloNutri { get; set; }
        public string PiernaNutri { get; set; }
        public string BrazosNutrii { get; set; }
        public string AntebrazoNutrii { get; set; }
        public string MuñecaNutrii { get; set; }
        public string PechoNutrii { get; set; }
        public string CinturaNutrii { get; set; }
        public string CaderaNutrii { get; set; }
        public string MusloSuperiorNutrii { get; set; }
        public string MusloMedioNutrii { get; set; }
        public string PiernaPerimetroNutrii { get; set; }
        public string TobilloPerimetroNutrii { get; set; }
        public Nullable<int> IdNutricion { get; set; }
    
        public virtual Nutricion Nutricion { get; set; }
    }
}
