//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecedentesMedicinaDelDeporte
    {
        public int IdAntecedentes { get; set; }
        public string Patologicos { get; set; }
        public string Quirurgicos { get; set; }
        public string Farmacologicos { get; set; }
        public string Familiares { get; set; }
        public string Traumatologicos { get; set; }
        public string LesionesDeportivas { get; set; }
        public string Alergicos { get; set; }
        public string PruebaCovid19 { get; set; }
        public string AnexosMedicinaDeportiva { get; set; }
        public Nullable<int> IdMedicina { get; set; }
    
        public virtual MedicinaDelDeporte MedicinaDelDeporte { get; set; }
    }
}
