//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecedentesFisioterapia
    {
        public int IdAntecedentesfisi { get; set; }
        public string MmssRealDer { get; set; }
        public string MmssRealizq { get; set; }
        public string AparenteMmssDer { get; set; }
        public string AparenteMmssIzq { get; set; }
        public string RealMmiiDer { get; set; }
        public string RealMmiiIzq { get; set; }
        public string AparenteMmiiDer { get; set; }
        public string AparenteMmiiIzq { get; set; }
        public string ObservacionesPosturaFisio { get; set; }
        public string BalanceoOjosAbiertos2 { get; set; }
        public string BalanceoOjosAbiertos1 { get; set; }
        public string BalanceoOjosAbiertos0 { get; set; }
        public string BalanceoOjosAbiertosObservaciones { get; set; }
        public string BalanceoOjosCerrados2 { get; set; }
        public string BalanceoOjosCerrados1 { get; set; }
        public string BalanceoOjosCerrados0 { get; set; }
        public string BalanceoOjosCerradosObservaciones { get; set; }
        public string FlexibilidadFisioterapia { get; set; }
        public Nullable<int> IdFisioterapia { get; set; }
    
        public virtual Fisioterapia Fisioterapia { get; set; }
    }
}
