//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DemograficoPsicologia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DemograficoPsicologia()
        {
            this.EnfermedadPersonalPsicologia = new HashSet<EnfermedadPersonalPsicologia>();
            this.FamiliaresPsicologia = new HashSet<FamiliaresPsicologia>();
            this.HistoriaFamiliaresPsicologia = new HashSet<HistoriaFamiliaresPsicologia>();
            this.SeguimientoPsicologia = new HashSet<SeguimientoPsicologia>();
            this.TestPsicologia = new HashSet<TestPsicologia>();
            this.VidapersonalPsicologia = new HashSet<VidapersonalPsicologia>();
        }
    
        public int IdDatosDemograficos { get; set; }
        public string CodigoPsicologia { get; set; }
        public string EstadoCivil { get; set; }
        public string NivelEducativo { get; set; }
        public string YoSoy { get; set; }
        public string NumHermanos { get; set; }
        public string VivoCon { get; set; }
        public string Actualmente { get; set; }
        public string Religion { get; set; }
        public string DependenciaEconomia { get; set; }
        public string AnexosPsicologia { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<long> NumIdentificacion { get; set; }
        public Nullable<int> IdCitaMedica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnfermedadPersonalPsicologia> EnfermedadPersonalPsicologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FamiliaresPsicologia> FamiliaresPsicologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaFamiliaresPsicologia> HistoriaFamiliaresPsicologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoPsicologia> SeguimientoPsicologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestPsicologia> TestPsicologia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VidapersonalPsicologia> VidapersonalPsicologia { get; set; }
    }
}
