//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaSocioeconomica
    {
        public int IdEncuestaSocieconomica { get; set; }
        public string Acueducto { get; set; }
        public string UniformeAdecuado { get; set; }
        public string TrasportePublico { get; set; }
        public string VecinosAmigables { get; set; }
        public string ProblemasVecinos { get; set; }
        public string CasaPropia { get; set; }
        public string PagasArriedno { get; set; }
        public string CuantoArriendo { get; set; }
        public string ServiciosCasa { get; set; }
        public string CuantosCuartos { get; set; }
        public string CuantosBaños { get; set; }
        public string TienesComputadora { get; set; }
        public string TienesAire { get; set; }
        public string CuantosAires { get; set; }
        public string CompartesCuarto { get; set; }
        public string CuantosCompartescuarto { get; set; }
        public string TienesCama { get; set; }
        public string TienesNeveraCasa { get; set; }
        public string TienesMascota { get; set; }
        public string TipoMascota { get; set; }
        public string TeGustaMusica { get; set; }
        public string SabesBailar { get; set; }
        public string DedicasTiempo { get; set; }
        public string EresFeliz { get; set; }
        public string Fotografico { get; set; }
        public Nullable<int> IdEncuestaDeportista { get; set; }
    
        public virtual EncuestaDeportistas EncuestaDeportistas { get; set; }
    }
}
