//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EncuestaDeportistas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EncuestaDeportistas()
        {
            this.EncuestaFamiliar = new HashSet<EncuestaFamiliar>();
            this.EncuestaSocioeconomica = new HashSet<EncuestaSocioeconomica>();
        }
    
        public int IdEncuestaDeportista { get; set; }
        public string IdentificacionDeportista { get; set; }
        public string PrimerNombreDepor { get; set; }
        public string SegundonombreDepor { get; set; }
        public string PrimerApellidoDepor { get; set; }
        public string SegundoApellidoDepor { get; set; }
        public Nullable<System.DateTime> FechaDepor { get; set; }
        public string EdadDepor { get; set; }
        public string DireccionDepor { get; set; }
        public string BarrioDepor { get; set; }
        public string DondeNacistesDepor { get; set; }
        public string NacionalidadDepor { get; set; }
        public string HospitalNacisteDepor { get; set; }
        public string DisciplinaDeportivaDepor { get; set; }
        public string PracticaDeporteDepor { get; set; }
        public string CategoriaDepor { get; set; }
        public string TelefonoDepor { get; set; }
        public string TienesTelefono { get; set; }
        public string CadaCuantoTelefono { get; set; }
        public string TienesRedesSociales { get; set; }
        public string CualesRedes { get; set; }
        public string Facebook { get; set; }
        public string Instagram { get; set; }
        public string Twitter { get; set; }
        public string CuantasPersonas { get; set; }
        public string ConocidosAmigos { get; set; }
        public string CuantosTotalAmigos { get; set; }
        public string MenoresCasa { get; set; }
        public string AgradaEntrenador { get; set; }
        public string MayoresCasa { get; set; }
        public string MaltratoVerbalEntrenador { get; set; }
        public string HermanosTienes { get; set; }
        public string CuantasHorasEntrenas { get; set; }
        public string InstalacionesEntrenas { get; set; }
        public string NoteGustaInstlaciones { get; set; }
        public string OtrosDeportes { get; set; }
        public string OtrosGustosDeportistas { get; set; }
        public string AguaDiaria { get; set; }
        public string HorasEntrenamiento { get; set; }
        public string TegustaPublico { get; set; }
        public string NotegustaHablarPublico { get; set; }
        public string VivesPadres { get; set; }
        public string ConquienVives { get; set; }
        public string VivesPension { get; set; }
        public string CuantoPagas { get; set; }
        public string ViveMadre { get; set; }
        public string VivePapa { get; set; }
        public string NombreMadreDepor { get; set; }
        public string NombrePadreDepor { get; set; }
        public string TrabajoPadreDepor { get; set; }
        public string TrabajoMadreDepor { get; set; }
        public string ProblemasPadre { get; set; }
        public string ProblemasMadre { get; set; }
        public string DependeEconomicamente { get; set; }
        public string GuantoGana { get; set; }
        public string VictimaConflicto { get; set; }
        public string TipoEtnia { get; set; }
        public string GeneroDepor { get; set; }
        public string NivelEstudio { get; set; }
        public string EstadoEconomico { get; set; }
        public string ComunaDepor { get; set; }
        public string UsuarioRegistra { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaFamiliar> EncuestaFamiliar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EncuestaSocioeconomica> EncuestaSocioeconomica { get; set; }
    }
}
