//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evolucionfisioterapia
    {
        public int IdTratamientofisio { get; set; }
        public string Sentadilla3 { get; set; }
        public string Sentadilla2 { get; set; }
        public string Sentadilla1 { get; set; }
        public string Sentadilla0 { get; set; }
        public string PasosValla3 { get; set; }
        public string PasosValle2 { get; set; }
        public string PasosValle1 { get; set; }
        public string PasosValle0 { get; set; }
        public string TijeraLinea3 { get; set; }
        public string TijeraLinea2 { get; set; }
        public string TijeraLinea1 { get; set; }
        public string TijeraLinea0 { get; set; }
        public string HombroActividad3 { get; set; }
        public string HombroActividad2 { get; set; }
        public string HombroActividad1 { get; set; }
        public string HombroActividad0 { get; set; }
        public string Pierna3 { get; set; }
        public string Pierna2 { get; set; }
        public string Pierna1 { get; set; }
        public string Pierna0 { get; set; }
        public string Pulgares3 { get; set; }
        public string Pulgares2 { get; set; }
        public string Pulgares1 { get; set; }
        public string Pulgares0 { get; set; }
        public string Tronco3 { get; set; }
        public string Tronco2 { get; set; }
        public string Tronco1 { get; set; }
        public string Tronco0 { get; set; }
        public string Planchas3 { get; set; }
        public string Planchas2 { get; set; }
        public string Planchas1 { get; set; }
        public string Planchas0 { get; set; }
        public string Sumatoria3 { get; set; }
        public string Sumatoria2 { get; set; }
        public string Sumatoria1 { get; set; }
        public string Sumatoria0 { get; set; }
        public string FlexoresTronco { get; set; }
        public string FlexoresPlancha { get; set; }
        public string FlexoresColumna { get; set; }
        public string FlexoresRecta { get; set; }
        public string ObservacionesGlobal { get; set; }
        public Nullable<System.DateTime> FechaTratamiento { get; set; }
        public Nullable<int> IdFisioterapia { get; set; }
    
        public virtual Fisioterapia Fisioterapia { get; set; }
    }
}
