//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenFisicoMedicinaDelDeporte
    {
        public int IdExamenFisico { get; set; }
        public string TensionArterial { get; set; }
        public Nullable<double> Peso { get; set; }
        public string IndiceMasaCorporal { get; set; }
        public string Postura { get; set; }
        public string FrecuenciaCardiaca { get; set; }
        public Nullable<double> Talla { get; set; }
        public string Tanner { get; set; }
        public string Grasos { get; set; }
        public string Muscular { get; set; }
        public string ExamenEspecifico { get; set; }
        public string Diagnostico { get; set; }
        public string Conducta { get; set; }
        public string FirmaMedico { get; set; }
        public Nullable<int> IdMedicina { get; set; }
    
        public virtual MedicinaDelDeporte MedicinaDelDeporte { get; set; }
    }
}
