//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliaresPsicologia
    {
        public int IdEnfermedadesFamiliares { get; set; }
        public string SustanciasPsicoFmlia { get; set; }
        public string EnferMentalesFmlia { get; set; }
        public string EnferCoronariasFmlia { get; set; }
        public string ObesidadFmlia { get; set; }
        public string CancerFmlia { get; set; }
        public string HipertensionFmlia { get; set; }
        public string EnferAlergicasFmlia { get; set; }
        public Nullable<int> IdDatosDemograficos { get; set; }
    
        public virtual DemograficoPsicologia DemograficoPsicologia { get; set; }
    }
}
