//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoriaClinicaFisioterapia
    {
        public int IdHistoriaClinicaFisio { get; set; }
        public string PatologicosClinicaFisio { get; set; }
        public string QuirurgicosClinicaFisio { get; set; }
        public string TraumaticosClinicaFisio { get; set; }
        public string FarmacologicosClinicaFisio { get; set; }
        public string FamiliaresClinicaFisio { get; set; }
        public string DiagnosticoMedicoClinicaFisio { get; set; }
        public string MotivoConsultaClinicaFisio { get; set; }
        public string DolorClinicaFisio { get; set; }
        public string EdemaClinicaFisio { get; set; }
        public string AlteradaClinicaFisio { get; set; }
        public string NoalterdaClinicaFisio { get; set; }
        public string ScreemFuncionalClinicaFisio { get; set; }
        public string DesempeñoClinicaFisio { get; set; }
        public string PosturaClinicaFisio { get; set; }
        public Nullable<System.DateTime> FechaClinicaFisio { get; set; }
        public string PlanTratamientoClinicaFisio { get; set; }
        public string EvolucionClinicaFisio1 { get; set; }
        public string EvolucionClinicaFisio2 { get; set; }
        public string EvolucionClinicaFisio3 { get; set; }
        public string EvolucionClinicaFisio4 { get; set; }
        public string EvolucionClinicaFisio5 { get; set; }
        public string EvolucionClinicaFisio6 { get; set; }
        public string EvolucionClinicaFisio7 { get; set; }
        public string EvolucionClinicaFisio8 { get; set; }
        public string EvolucionClinicaFisio9 { get; set; }
        public string EvolucionClinicaFisio10 { get; set; }
        public string FirmaEvolucionClinica { get; set; }
        public Nullable<long> NumIdentificacion { get; set; }
        public Nullable<int> IdFisioterapia { get; set; }
        public Nullable<int> IdMedicina { get; set; }
    
        public virtual Fisioterapia Fisioterapia { get; set; }
    }
}
