//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nutricion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nutricion()
        {
            this.AnamnesisNutricion = new HashSet<AnamnesisNutricion>();
            this.ControlNutricion = new HashSet<ControlNutricion>();
            this.SeguimientoNutricion = new HashSet<SeguimientoNutricion>();
        }
    
        public int IdNutricion { get; set; }
        public string CodNutricion { get; set; }
        public string AntecedentesNutri { get; set; }
        public string FamiliaresNutri { get; set; }
        public string PersonalesNutri { get; set; }
        public string FarmacologicosNutri { get; set; }
        public string GinecologicoNutri { get; set; }
        public string SueñoNutri { get; set; }
        public string PielNutri { get; set; }
        public string ApetitoNutri { get; set; }
        public string FracturaNutri { get; set; }
        public string AspectoFisicoNutri { get; set; }
        public string PieNutri { get; set; }
        public string TiempoRecuperacionNutri { get; set; }
        public string BioquimicoNutri { get; set; }
        public string HidratacionNutri { get; set; }
        public string HorarioActividadNutri { get; set; }
        public string AnexosNutricion { get; set; }
        public string UsuarioRegistro { get; set; }
        public Nullable<System.DateTime> FechaRegistroNutri { get; set; }
        public Nullable<long> NumIdentificacion { get; set; }
        public Nullable<int> IdCitaMedica { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnamnesisNutricion> AnamnesisNutricion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlNutricion> ControlNutricion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeguimientoNutricion> SeguimientoNutricion { get; set; }
    }
}
