//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ocupacion
    {
        public int IdOcupacion { get; set; }
        public string Ocupacion1 { get; set; }
        public string NivelEducativo { get; set; }
        public string Institucion { get; set; }
        public string TelefonoInstitucion { get; set; }
        public string DirectorGrado { get; set; }
        public Nullable<double> Peso { get; set; }
        public Nullable<double> Estatura { get; set; }
        public string TallaCamisa { get; set; }
        public Nullable<int> TallaPantalon { get; set; }
        public Nullable<int> TallaCalzado { get; set; }
        public string TallaSudadera { get; set; }
        public Nullable<int> NumeroHijos { get; set; }
        public Nullable<int> IdDeportista { get; set; }
    
        public virtual Deportistas Deportistas { get; set; }
    }
}
