//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoPsicologia
    {
        public int IdSeguimiento { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string EvolucionPsicologia { get; set; }
        public string TestsPsicologico { get; set; }
        public string FirmaDocPsicologia { get; set; }
        public Nullable<long> NumIdentificacion { get; set; }
        public Nullable<int> IdDatosDemograficos { get; set; }
        public Nullable<int> IdMedicina { get; set; }
    
        public virtual DemograficoPsicologia DemograficoPsicologia { get; set; }
    }
}
