//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeguimientoMedicinaDeporte
    {
        public int IdSeguimientoDeportiva { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string DiagnosticoDeportiva { get; set; }
        public string EvolucionDeportiva { get; set; }
        public string ConductaDeportiva { get; set; }
        public string FirmaDeportiva { get; set; }
        public Nullable<long> NumIdentificacion { get; set; }
        public Nullable<int> IdMedicina { get; set; }
    
        public virtual MedicinaDelDeporte MedicinaDelDeporte { get; set; }
    }
}
