//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOMEDICO.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VidapersonalPsicologia
    {
        public int IdPersonalFisi { get; set; }
        public string EntrenamientoActualPsi { get; set; }
        public string HorasDiariasPsi { get; set; }
        public string NumeroSesionesPsi { get; set; }
        public string LugarPsi { get; set; }
        public string NombreEntrenadorPsi { get; set; }
        public string InicioDeportePsi { get; set; }
        public string EntrenamiendoPsi { get; set; }
        public string CompeticionPsi { get; set; }
        public string EntrenamientoGuiadoPsi { get; set; }
        public string MeApoyanPsi { get; set; }
        public string CompromisoPsi { get; set; }
        public string EntramientoPsicologicoPsi { get; set; }
        public string ObservacionesPsi { get; set; }
        public string ResultadosPsi { get; set; }
        public string RecomendacionesPsi { get; set; }
        public string RemisionPsi { get; set; }
        public string SeguimientoPsi { get; set; }
        public string FirmaDoctorPsicologia { get; set; }
        public Nullable<int> IdDatosDemograficos { get; set; }
    
        public virtual DemograficoPsicologia DemograficoPsicologia { get; set; }
    }
}
